---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: pages
  label: Pages
  create: documents
  match: "**/*.md"
  templates:
  - pages
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "**/*.md"
  templates:
  - blog
- type: directory
  path: events
  label: events
  create: documents
  match: "**/*.md"
  templates:
  - events
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dist
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
